name: unique_color
description: Generate a time invariant hex color.
version: 1.0.0
repository: https://github.com/iberatkaya/unique_color

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  pedantic: ^1.9.0
  test: any
